name: Publish Toolset to WordPress

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish full repository via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./.localstorage/ECE/
          server-dir: /campaign_files/ECE/

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
